var _RawData = [
  {
    "text": "there seem to be infinite ways to meet people online and in-person",
    "y2016": false,
    "need": false,
    "matters": false,
    "fact": true,
    "command": false,
    "I": false,
    "We": false,
    "You": false,
    "3rdPersonSingular": false,
    "business": false,
    "politics": false,
    "popCulture": false,
    "scienceTech": true,
    "religion": false,
    "education": false,
    "global": true,
    "community": true,
    "personal": false,
    "fashion": false,
    "military": false
  },
  {
    "text": "our students are hurting",
    "y2016": false,
    "need": false,
    "matters": false,
    "fact": true,
    "command": false,
    "I": false,
    "We": false,
    "You": false,
    "3rdPersonSingular": false,
    "business": false,
    "politics": false,
    "popCulture": false,
    "scienceTech": false,
    "religion": false,
    "education": true,
    "global": true,
    "community": true,
    "personal": false,
    "fashion": false,
    "military": false
  },
  {
    "text": "he has to look forward",
    "y2016": false,
    "need": false,
    "matters": false,
    "fact": false,
    "command": true,
    "I": false,
    "We": false,
    "You": false,
    "3rdPersonSingular": true,
    "business": false,
    "politics": false,
    "popCulture": false,
    "scienceTech": false,
    "religion": false,
    "education": false,
    "global": false,
    "community": false,
    "personal": true,
    "fashion": false,
    "military": false
  },
  {
    "text": "I appreciate women",
    "y2016": false,
    "need": false,
    "matters": false,
    "fact": true,
    "command": false,
    "I": true,
    "We": false,
    "You": false,
    "3rdPersonSingular": false,
    "business": false,
    "politics": false,
    "popCulture": false,
    "scienceTech": false,
    "religion": false,
    "education": false,
    "global": false,
    "community": false,
    "personal": true,
    "fashion": false,
    "military": false
  },
  {
    "text": "everything is on the table",
    "y2016": false,
    "need": false,
    "matters": false,
    "fact": true,
    "command": false,
    "I": false,
    "We": false,
    "You": false,
    "3rdPersonSingular": false,
    "business": false,
    "politics": false,
    "popCulture": false,
    "scienceTech": false,
    "religion": false,
    "education": false,
    "global": false,
    "community": false,
    "personal": false,
    "fashion": false,
    "military": false
  },
  {
    "text": "I know she loves our family",
    "y2016": false,
    "need": false,
    "matters": false,
    "fact": true,
    "command": false,
    "I": true,
    "We": false,
    "You": false,
    "3rdPersonSingular": false,
    "business": false,
    "politics": false,
    "popCulture": false,
    "scienceTech": false,
    "religion": false,
    "education": false,
    "global": false,
    "community": false,
    "personal": true,
    "fashion": false,
    "military": false
  },
  {
    "text": "William and Kate are keenly aware of the fleeting nature of their current arrangement",
    "y2016": false,
    "need": false,
    "matters": false,
    "fact": true,
    "command": false,
    "I": false,
    "We": false,
    "You": false,
    "3rdPersonSingular": true,
    "business": false,
    "politics": true,
    "popCulture": true,
    "scienceTech": false,
    "religion": false,
    "education": false,
    "global": false,
    "community": false,
    "personal": true,
    "fashion": false,
    "military": false
  },
  {
    "text": "our crazy world needs humor",
    "y2016": false,
    "need": false,
    "matters": false,
    "fact": false,
    "command": false,
    "I": false,
    "We": true,
    "You": false,
    "3rdPersonSingular": false,
    "business": false,
    "politics": false,
    "popCulture": false,
    "scienceTech": false,
    "religion": false,
    "education": false,
    "global": true,
    "community": false,
    "personal": false,
    "fashion": false,
    "military": false
  },
  {
    "text": "we need people to give back to their public lands",
    "y2016": false,
    "need": true,
    "matters": false,
    "fact": false,
    "command": true,
    "I": false,
    "We": true,
    "You": false,
    "3rdPersonSingular": false,
    "business": false,
    "politics": true,
    "popCulture": false,
    "scienceTech": false,
    "religion": false,
    "education": false,
    "global": false,
    "community": true,
    "personal": true,
    "fashion": false,
    "military": false
  },
  {
    "text": "water plays a critical role in producing oil",
    "y2016": false,
    "need": false,
    "matters": false,
    "fact": true,
    "command": false,
    "I": false,
    "We": false,
    "You": false,
    "3rdPersonSingular": false,
    "business": true,
    "politics": false,
    "popCulture": false,
    "scienceTech": true,
    "religion": false,
    "education": false,
    "global": true,
    "community": false,
    "personal": false,
    "fashion": false,
    "military": false
  },
  {
    "text": "she'll need to listen to her own advice",
    "y2016": false,
    "need": false,
    "matters": false,
    "fact": false,
    "command": true,
    "I": false,
    "We": false,
    "You": false,
    "3rdPersonSingular": true,
    "business": false,
    "politics": false,
    "popCulture": false,
    "scienceTech": false,
    "religion": false,
    "education": false,
    "global": false,
    "community": false,
    "personal": true,
    "fashion": false,
    "military": false
  },
  {
    "text": "teachers have to consider how digital tools may be effectively utilized in their content curricula to build literacy skills among adolescents",
    "y2016": false,
    "need": false,
    "matters": false,
    "fact": false,
    "command": true,
    "I": false,
    "We": false,
    "You": false,
    "3rdPersonSingular": false,
    "business": false,
    "politics": false,
    "popCulture": false,
    "scienceTech": true,
    "religion": false,
    "education": true,
    "global": false,
    "community": true,
    "personal": false,
    "fashion": false,
    "military": false
  },
  {
    "text": "change has become a constant",
    "y2016": false,
    "need": false,
    "matters": false,
    "fact": true,
    "command": false,
    "I": false,
    "We": false,
    "You": false,
    "3rdPersonSingular": false,
    "business": false,
    "politics": false,
    "popCulture": false,
    "scienceTech": false,
    "religion": false,
    "education": false,
    "global": true,
    "community": false,
    "personal": false,
    "fashion": false,
    "military": false
  },
  {
    "text": "white folks not wanting to know what went on in Little Brier was a good thing",
    "y2016": false,
    "need": false,
    "matters": false,
    "fact": true,
    "command": false,
    "I": false,
    "We": false,
    "You": false,
    "3rdPersonSingular": false,
    "business": false,
    "politics": false,
    "popCulture": false,
    "scienceTech": false,
    "religion": false,
    "education": false,
    "global": false,
    "community": true,
    "personal": false,
    "fashion": false,
    "military": false
  },
  {
    "text": "we need the Great Tradition's reflection",
    "y2016": false,
    "need": false,
    "matters": false,
    "fact": false,
    "command": false,
    "I": false,
    "We": true,
    "You": false,
    "3rdPersonSingular": false,
    "business": false,
    "politics": false,
    "popCulture": false,
    "scienceTech": false,
    "religion": true,
    "education": false,
    "global": false,
    "community": true,
    "personal": true,
    "fashion": false,
    "military": false
  },
  {
    "text": "the country needs scouting",
    "y2016": false,
    "need": true,
    "matters": false,
    "fact": true,
    "command": false,
    "I": false,
    "We": false,
    "You": false,
    "3rdPersonSingular": false,
    "business": false,
    "politics": false,
    "popCulture": false,
    "scienceTech": false,
    "religion": false,
    "education": true,
    "global": false,
    "community": true,
    "personal": false,
    "fashion": false,
    "military": false
  },
  {
    "text": "FATHERS MATTER",
    "y2016": false,
    "need": false,
    "matters": false,
    "fact": true,
    "command": false,
    "I": false,
    "We": false,
    "You": false,
    "3rdPersonSingular": false,
    "business": false,
    "politics": false,
    "popCulture": false,
    "scienceTech": false,
    "religion": false,
    "education": false,
    "global": false,
    "community": true,
    "personal": true,
    "fashion": false,
    "military": false
  },
  {
    "text": "a collaborative culture will be supported by upper management keenly aware of the impact of diversity and fairness, perhaps",
    "y2016": false,
    "need": false,
    "matters": false,
    "fact": true,
    "command": false,
    "I": false,
    "We": false,
    "You": false,
    "3rdPersonSingular": false,
    "business": true,
    "politics": false,
    "popCulture": false,
    "scienceTech": false,
    "religion": false,
    "education": false,
    "global": false,
    "community": true,
    "personal": false,
    "fashion": false,
    "military": false
  },
  {
    "text": "pure cover corners are coveted",
    "y2016": false,
    "need": false,
    "matters": false,
    "fact": true,
    "command": false,
    "I": false,
    "We": false,
    "You": false,
    "3rdPersonSingular": false,
    "business": false,
    "politics": false,
    "popCulture": true,
    "scienceTech": false,
    "religion": false,
    "education": false,
    "global": false,
    "community": false,
    "personal": false,
    "fashion": false,
    "military": false
  },
  {
    "text": "evangelicals need to know the truth is clearly otherwise",
    "y2016": false,
    "need": false,
    "matters": false,
    "fact": false,
    "command": true,
    "I": false,
    "We": false,
    "You": false,
    "3rdPersonSingular": false,
    "business": false,
    "politics": false,
    "popCulture": false,
    "scienceTech": false,
    "religion": true,
    "education": false,
    "global": false,
    "community": true,
    "personal": true,
    "fashion": false,
    "military": false
  },
  {
    "text": "our technology is zapping our memories",
    "y2016": false,
    "need": false,
    "matters": false,
    "fact": true,
    "command": false,
    "I": false,
    "We": false,
    "You": false,
    "3rdPersonSingular": false,
    "business": false,
    "politics": false,
    "popCulture": false,
    "scienceTech": true,
    "religion": false,
    "education": false,
    "global": true,
    "community": false,
    "personal": false,
    "fashion": false,
    "military": false
  },
  {
    "text": "the faith based community is needed",
    "y2016": false,
    "need": true,
    "matters": false,
    "fact": true,
    "command": false,
    "I": false,
    "We": false,
    "You": false,
    "3rdPersonSingular": false,
    "business": false,
    "politics": false,
    "popCulture": false,
    "scienceTech": false,
    "religion": true,
    "education": false,
    "global": false,
    "community": true,
    "personal": false,
    "fashion": false,
    "military": false
  },
  {
    "text": "the government is sticking its nose in your business",
    "y2016": false,
    "need": false,
    "matters": false,
    "fact": true,
    "command": false,
    "I": false,
    "We": false,
    "You": true,
    "3rdPersonSingular": false,
    "business": false,
    "politics": true,
    "popCulture": false,
    "scienceTech": false,
    "religion": false,
    "education": false,
    "global": true,
    "community": false,
    "personal": false,
    "fashion": false,
    "military": false
  },
  {
    "text": "the D.C. population has a good reason to be nervous",
    "y2016": false,
    "need": false,
    "matters": false,
    "fact": true,
    "command": false,
    "I": false,
    "We": false,
    "You": false,
    "3rdPersonSingular": false,
    "business": false,
    "politics": true,
    "popCulture": false,
    "scienceTech": false,
    "religion": false,
    "education": false,
    "global": false,
    "community": true,
    "personal": false,
    "fashion": false,
    "military": false
  },
  {
    "text": "courtesy, kindness, and good manners are all necessary",
    "y2016": false,
    "need": true,
    "matters": false,
    "fact": true,
    "command": false,
    "I": false,
    "We": false,
    "You": false,
    "3rdPersonSingular": false,
    "business": false,
    "politics": false,
    "popCulture": false,
    "scienceTech": false,
    "religion": false,
    "education": false,
    "global": true,
    "community": true,
    "personal": false,
    "fashion": false,
    "military": false
  },
  {
    "text": "we need visions",
    "y2016": false,
    "need": true,
    "matters": false,
    "fact": true,
    "command": false,
    "I": false,
    "We": true,
    "You": false,
    "3rdPersonSingular": false,
    "business": false,
    "politics": false,
    "popCulture": false,
    "scienceTech": false,
    "religion": false,
    "education": false,
    "global": false,
    "community": false,
    "personal": true,
    "fashion": false,
    "military": false
  },
  {
    "text": "historically black colleges and universities are needed",
    "y2016": false,
    "need": true,
    "matters": false,
    "fact": true,
    "command": false,
    "I": false,
    "We": false,
    "You": false,
    "3rdPersonSingular": false,
    "business": false,
    "politics": false,
    "popCulture": false,
    "scienceTech": false,
    "religion": false,
    "education": true,
    "global": false,
    "community": true,
    "personal": false,
    "fashion": false,
    "military": false
  },
  {
    "text": "the benefits of research flow throughout the world",
    "y2016": false,
    "need": false,
    "matters": false,
    "fact": true,
    "command": false,
    "I": false,
    "We": false,
    "You": false,
    "3rdPersonSingular": false,
    "business": false,
    "politics": false,
    "popCulture": false,
    "scienceTech": true,
    "religion": false,
    "education": false,
    "global": false,
    "community": false,
    "personal": false,
    "fashion": false,
    "military": false
  },
  {
    "text": "maybe we need hermits",
    "y2016": false,
    "need": true,
    "matters": false,
    "fact": true,
    "command": false,
    "I": false,
    "We": true,
    "You": false,
    "3rdPersonSingular": false,
    "business": false,
    "politics": false,
    "popCulture": false,
    "scienceTech": false,
    "religion": true,
    "education": false,
    "global": false,
    "community": true,
    "personal": false,
    "fashion": false,
    "military": false
  },
  {
    "text": "thinking critically is a skill students need",
    "y2016": false,
    "need": true,
    "matters": false,
    "fact": true,
    "command": false,
    "I": false,
    "We": false,
    "You": false,
    "3rdPersonSingular": false,
    "business": false,
    "politics": false,
    "popCulture": false,
    "scienceTech": false,
    "religion": false,
    "education": true,
    "global": true,
    "community": true,
    "personal": false,
    "fashion": false,
    "military": false
  },
  {
    "text": "there is a need for bilateral and multilateral assistance to be coordinated for maximal effect, to avoid duplication and gaps, and to focus on measureable results",
    "y2016": false,
    "need": true,
    "matters": false,
    "fact": true,
    "command": false,
    "I": false,
    "We": false,
    "You": false,
    "3rdPersonSingular": false,
    "business": true,
    "politics": true,
    "popCulture": false,
    "scienceTech": false,
    "religion": false,
    "education": false,
    "global": true,
    "community": false,
    "personal": false,
    "fashion": false,
    "military": false
  },
  {
    "text": "music educators must explore new, creative, and effective ways to communicate with an ever-changing student population",
    "y2016": false,
    "need": false,
    "matters": false,
    "fact": false,
    "command": true,
    "I": false,
    "We": false,
    "You": false,
    "3rdPersonSingular": false,
    "business": false,
    "politics": false,
    "popCulture": false,
    "scienceTech": false,
    "religion": false,
    "education": true,
    "global": false,
    "community": true,
    "personal": false,
    "fashion": false,
    "military": false
  },
  {
    "text": "becoming literate and educated is all about understanding, acquiring knowledge, and actively using it",
    "y2016": false,
    "need": false,
    "matters": false,
    "fact": true,
    "command": false,
    "I": false,
    "We": false,
    "You": false,
    "3rdPersonSingular": false,
    "business": false,
    "politics": false,
    "popCulture": false,
    "scienceTech": true,
    "religion": false,
    "education": true,
    "global": false,
    "community": false,
    "personal": false,
    "fashion": false,
    "military": false
  },
  {
    "text": "I know that there is a God",
    "y2016": false,
    "need": false,
    "matters": false,
    "fact": true,
    "command": false,
    "I": true,
    "We": false,
    "You": false,
    "3rdPersonSingular": false,
    "business": false,
    "politics": false,
    "popCulture": false,
    "scienceTech": false,
    "religion": true,
    "education": false,
    "global": false,
    "community": false,
    "personal": true,
    "fashion": false,
    "military": false
  },
  {
    "text": "education is the gateway to a middle-class life",
    "y2016": false,
    "need": false,
    "matters": false,
    "fact": true,
    "command": false,
    "I": false,
    "We": false,
    "You": false,
    "3rdPersonSingular": false,
    "business": false,
    "politics": false,
    "popCulture": false,
    "scienceTech": false,
    "religion": false,
    "education": true,
    "global": true,
    "community": true,
    "personal": false,
    "fashion": false,
    "military": false
  },
  {
    "text": "they're gonna need a tremendous strength",
    "y2016": false,
    "need": true,
    "matters": false,
    "fact": false,
    "command": false,
    "I": false,
    "We": false,
    "You": false,
    "3rdPersonSingular": false,
    "business": false,
    "politics": false,
    "popCulture": false,
    "scienceTech": false,
    "religion": false,
    "education": false,
    "global": false,
    "community": true,
    "personal": true,
    "fashion": false,
    "military": false
  },
  {
    "text": "the world is broken",
    "y2016": false,
    "need": false,
    "matters": false,
    "fact": true,
    "command": false,
    "I": false,
    "We": false,
    "You": false,
    "3rdPersonSingular": false,
    "business": false,
    "politics": false,
    "popCulture": false,
    "scienceTech": false,
    "religion": false,
    "education": false,
    "global": true,
    "community": false,
    "personal": false,
    "fashion": false,
    "military": false
  },
  {
    "text": "we want men",
    "y2016": false,
    "need": false,
    "matters": false,
    "fact": true,
    "command": false,
    "I": false,
    "We": true,
    "You": false,
    "3rdPersonSingular": false,
    "business": false,
    "politics": false,
    "popCulture": false,
    "scienceTech": false,
    "religion": false,
    "education": false,
    "global": false,
    "community": true,
    "personal": true,
    "fashion": false,
    "military": false
  },
  {
    "text": "Catholics must be willing to witness a communion in Christ that transcends political divisions",
    "y2016": false,
    "need": false,
    "matters": false,
    "fact": false,
    "command": true,
    "I": false,
    "We": false,
    "You": false,
    "3rdPersonSingular": false,
    "business": false,
    "politics": true,
    "popCulture": false,
    "scienceTech": false,
    "religion": true,
    "education": false,
    "global": false,
    "community": true,
    "personal": false,
    "fashion": false,
    "military": false
  },
  {
    "text": "cities and industries depend on frequent, affordable air service to remain competitive in the global economy",
    "y2016": false,
    "need": false,
    "matters": false,
    "fact": true,
    "command": false,
    "I": false,
    "We": false,
    "You": false,
    "3rdPersonSingular": false,
    "business": true,
    "politics": false,
    "popCulture": false,
    "scienceTech": false,
    "religion": false,
    "education": false,
    "global": true,
    "community": false,
    "personal": false,
    "fashion": false,
    "military": false
  },
  {
    "text": "parents have to insert themselves as self-styled activists on their children's behalf",
    "y2016": false,
    "need": false,
    "matters": false,
    "fact": false,
    "command": true,
    "I": false,
    "We": false,
    "You": false,
    "3rdPersonSingular": false,
    "business": false,
    "politics": true,
    "popCulture": false,
    "scienceTech": false,
    "religion": false,
    "education": true,
    "global": false,
    "community": true,
    "personal": true,
    "fashion": false,
    "military": false
  },
  {
    "text": "business and industry are dependent upon an economic system that rewards innovation",
    "y2016": false,
    "need": false,
    "matters": false,
    "fact": true,
    "command": false,
    "I": false,
    "We": false,
    "You": false,
    "3rdPersonSingular": false,
    "business": true,
    "politics": true,
    "popCulture": false,
    "scienceTech": true,
    "religion": false,
    "education": false,
    "global": false,
    "community": false,
    "personal": false,
    "fashion": false,
    "military": false
  },
  {
    "text": "you can expect your shot tendencies to reappear",
    "y2016": false,
    "need": false,
    "matters": false,
    "fact": true,
    "command": false,
    "I": false,
    "We": false,
    "You": true,
    "3rdPersonSingular": false,
    "business": false,
    "politics": false,
    "popCulture": true,
    "scienceTech": false,
    "religion": false,
    "education": false,
    "global": false,
    "community": false,
    "personal": false,
    "fashion": false,
    "military": false
  },
  {
    "text": "the Santa Maria village council needs wind turbines",
    "y2016": false,
    "need": true,
    "matters": false,
    "fact": true,
    "command": false,
    "I": false,
    "We": false,
    "You": false,
    "3rdPersonSingular": false,
    "business": false,
    "politics": false,
    "popCulture": false,
    "scienceTech": true,
    "religion": false,
    "education": false,
    "global": false,
    "community": true,
    "personal": false,
    "fashion": false,
    "military": false
  },
  {
    "text": "America needs to hear Woody Guthrie's songs",
    "y2016": false,
    "need": false,
    "matters": false,
    "fact": false,
    "command": true,
    "I": false,
    "We": false,
    "You": false,
    "3rdPersonSingular": false,
    "business": false,
    "politics": false,
    "popCulture": true,
    "scienceTech": false,
    "religion": false,
    "education": false,
    "global": true,
    "community": false,
    "personal": false,
    "fashion": false,
    "military": false
  },
  {
    "text": "sustained but strategic support could produce blockbuster innovations with the potential to meaningfully change the energy mix",
    "y2016": false,
    "need": false,
    "matters": false,
    "fact": true,
    "command": false,
    "I": false,
    "We": false,
    "You": false,
    "3rdPersonSingular": false,
    "business": false,
    "politics": false,
    "popCulture": false,
    "scienceTech": true,
    "religion": false,
    "education": false,
    "global": false,
    "community": false,
    "personal": false,
    "fashion": false,
    "military": false
  },
  {
    "text": "I love you",
    "y2016": false,
    "need": false,
    "matters": false,
    "fact": true,
    "command": false,
    "I": true,
    "We": false,
    "You": true,
    "3rdPersonSingular": false,
    "business": false,
    "politics": false,
    "popCulture": false,
    "scienceTech": false,
    "religion": false,
    "education": false,
    "global": false,
    "community": false,
    "personal": true,
    "fashion": false,
    "military": false
  },
  {
    "text": "we need support networks",
    "y2016": false,
    "need": true,
    "matters": false,
    "fact": true,
    "command": false,
    "I": false,
    "We": true,
    "You": false,
    "3rdPersonSingular": false,
    "business": false,
    "politics": false,
    "popCulture": false,
    "scienceTech": false,
    "religion": false,
    "education": false,
    "global": false,
    "community": true,
    "personal": true,
    "fashion": false,
    "military": false
  },
  {
    "text": "growing up is hard to do, perhaps",
    "y2016": false,
    "need": false,
    "matters": false,
    "fact": true,
    "command": false,
    "I": false,
    "We": false,
    "You": false,
    "3rdPersonSingular": false,
    "business": false,
    "politics": false,
    "popCulture": false,
    "scienceTech": false,
    "religion": false,
    "education": false,
    "global": false,
    "community": false,
    "personal": true,
    "fashion": false,
    "military": false
  },
  {
    "text": "we've got to get control of our states",
    "y2016": false,
    "need": false,
    "matters": false,
    "fact": false,
    "command": true,
    "I": false,
    "We": true,
    "You": false,
    "3rdPersonSingular": false,
    "business": false,
    "politics": true,
    "popCulture": false,
    "scienceTech": false,
    "religion": false,
    "education": false,
    "global": true,
    "community": true,
    "personal": false,
    "fashion": false,
    "military": false
  },
  {
    "text": "he missed his father",
    "y2016": false,
    "need": false,
    "matters": false,
    "fact": true,
    "command": false,
    "I": false,
    "We": false,
    "You": true,
    "3rdPersonSingular": false,
    "business": false,
    "politics": false,
    "popCulture": false,
    "scienceTech": false,
    "religion": false,
    "education": false,
    "global": false,
    "community": false,
    "personal": false,
    "fashion": false,
    "military": false
  },
  {
    "text": "they want to know where their money is going",
    "y2016": false,
    "need": false,
    "matters": false,
    "fact": true,
    "command": false,
    "I": false,
    "We": false,
    "You": false,
    "3rdPersonSingular": false,
    "business": false,
    "politics": true,
    "popCulture": false,
    "scienceTech": false,
    "religion": false,
    "education": false,
    "global": false,
    "community": true,
    "personal": false,
    "fashion": false,
    "military": false
  },
  {
    "text": "stay informed",
    "y2016": false,
    "need": false,
    "matters": false,
    "fact": false,
    "command": true,
    "I": false,
    "We": false,
    "You": true,
    "3rdPersonSingular": false,
    "business": false,
    "politics": true,
    "popCulture": false,
    "scienceTech": false,
    "religion": false,
    "education": true,
    "global": true,
    "community": false,
    "personal": false,
    "fashion": false,
    "military": false
  },
  {
    "text": "it's critically important that ovarian cancer advocates come together to support this important research",
    "y2016": false,
    "need": false,
    "matters": false,
    "fact": true,
    "command": false,
    "I": false,
    "We": false,
    "You": false,
    "3rdPersonSingular": false,
    "business": false,
    "politics": false,
    "popCulture": false,
    "scienceTech": true,
    "religion": false,
    "education": false,
    "global": false,
    "community": false,
    "personal": false,
    "fashion": false,
    "military": false
  },
  {
    "text": "the stage is set for suspicious thinking",
    "y2016": false,
    "need": false,
    "matters": false,
    "fact": true,
    "command": false,
    "I": false,
    "We": false,
    "You": false,
    "3rdPersonSingular": false,
    "business": false,
    "politics": true,
    "popCulture": false,
    "scienceTech": false,
    "religion": false,
    "education": false,
    "global": false,
    "community": false,
    "personal": false,
    "fashion": false,
    "military": false
  },
  {
    "text": "the smell of earth on our hands keeps us connected to the real world in a way that a virtual stream of tweets, posts, videos, and links can not",
    "y2016": false,
    "need": false,
    "matters": false,
    "fact": true,
    "command": false,
    "I": false,
    "We": false,
    "You": false,
    "3rdPersonSingular": false,
    "business": false,
    "politics": false,
    "popCulture": false,
    "scienceTech": true,
    "religion": false,
    "education": false,
    "global": false,
    "community": true,
    "personal": false,
    "fashion": false,
    "military": false
  },
  {
    "text": "let the dreams of Lombardi trophies dance in your head",
    "y2016": false,
    "need": false,
    "matters": false,
    "fact": false,
    "command": true,
    "I": false,
    "We": false,
    "You": true,
    "3rdPersonSingular": false,
    "business": false,
    "politics": false,
    "popCulture": true,
    "scienceTech": false,
    "religion": false,
    "education": false,
    "global": false,
    "community": false,
    "personal": true,
    "fashion": false,
    "military": false
  },
  {
    "text": "people need messages about living well within our geography and current circumstances",
    "y2016": false,
    "need": true,
    "matters": false,
    "fact": true,
    "command": false,
    "I": false,
    "We": false,
    "You": false,
    "3rdPersonSingular": false,
    "business": false,
    "politics": false,
    "popCulture": false,
    "scienceTech": false,
    "religion": false,
    "education": false,
    "global": false,
    "community": true,
    "personal": false,
    "fashion": false,
    "military": false
  },
  {
    "text": "Arab democracy needs advocates",
    "y2016": false,
    "need": false,
    "matters": false,
    "fact": true,
    "command": false,
    "I": false,
    "We": false,
    "You": false,
    "3rdPersonSingular": false,
    "business": false,
    "politics": true,
    "popCulture": false,
    "scienceTech": false,
    "religion": false,
    "education": false,
    "global": true,
    "community": true,
    "personal": false,
    "fashion": false,
    "military": false
  },
  {
    "text": "the businesses downtown need to be patronized",
    "y2016": false,
    "need": false,
    "matters": false,
    "fact": false,
    "command": true,
    "I": false,
    "We": false,
    "You": false,
    "3rdPersonSingular": false,
    "business": true,
    "politics": false,
    "popCulture": false,
    "scienceTech": false,
    "religion": false,
    "education": false,
    "global": false,
    "community": true,
    "personal": false,
    "fashion": false,
    "military": false
  },
  {
    "text": "people are concerned about helping those who are right around the corner from them",
    "y2016": false,
    "need": false,
    "matters": false,
    "fact": true,
    "command": false,
    "I": false,
    "We": false,
    "You": false,
    "3rdPersonSingular": false,
    "business": false,
    "politics": true,
    "popCulture": false,
    "scienceTech": false,
    "religion": false,
    "education": false,
    "global": false,
    "community": true,
    "personal": false,
    "fashion": false,
    "military": false
  },
  {
    "text": "engineers need to bring their experience and knowledge to bear to address low-probability, high-consequence system failures",
    "y2016": false,
    "need": false,
    "matters": false,
    "fact": false,
    "command": true,
    "I": false,
    "We": false,
    "You": false,
    "3rdPersonSingular": false,
    "business": false,
    "politics": false,
    "popCulture": false,
    "scienceTech": true,
    "religion": false,
    "education": false,
    "global": false,
    "community": false,
    "personal": false,
    "fashion": false,
    "military": false
  },
  {
    "text": "the people of America are paying attention to what is going on",
    "y2016": false,
    "need": false,
    "matters": false,
    "fact": true,
    "command": false,
    "I": false,
    "We": false,
    "You": false,
    "3rdPersonSingular": false,
    "business": false,
    "politics": true,
    "popCulture": false,
    "scienceTech": false,
    "religion": false,
    "education": false,
    "global": true,
    "community": true,
    "personal": false,
    "fashion": false,
    "military": false
  },
  {
    "text": "we need your voice",
    "y2016": false,
    "need": true,
    "matters": false,
    "fact": true,
    "command": false,
    "I": false,
    "We": true,
    "You": false,
    "3rdPersonSingular": false,
    "business": false,
    "politics": true,
    "popCulture": false,
    "scienceTech": false,
    "religion": false,
    "education": false,
    "global": true,
    "community": true,
    "personal": true,
    "fashion": false,
    "military": false
  },
  {
    "text": "Port-au-Prince is a city that moves to the rising and setting of the sun",
    "y2016": false,
    "need": false,
    "matters": false,
    "fact": true,
    "command": false,
    "I": false,
    "We": false,
    "You": false,
    "3rdPersonSingular": false,
    "business": false,
    "politics": false,
    "popCulture": false,
    "scienceTech": false,
    "religion": false,
    "education": false,
    "global": false,
    "community": true,
    "personal": false,
    "fashion": false,
    "military": false
  },
  {
    "text": "the world needs heroes",
    "y2016": false,
    "need": true,
    "matters": false,
    "fact": true,
    "command": false,
    "I": false,
    "We": false,
    "You": false,
    "3rdPersonSingular": false,
    "business": false,
    "politics": false,
    "popCulture": false,
    "scienceTech": false,
    "religion": false,
    "education": false,
    "global": true,
    "community": false,
    "personal": false,
    "fashion": false,
    "military": false
  },
  {
    "text": "Your mom needs you",
    "y2016": false,
    "need": true,
    "matters": false,
    "fact": true,
    "command": false,
    "I": false,
    "We": false,
    "You": true,
    "3rdPersonSingular": false,
    "business": false,
    "politics": false,
    "popCulture": false,
    "scienceTech": false,
    "religion": false,
    "education": false,
    "global": false,
    "community": false,
    "personal": true,
    "fashion": false,
    "military": false
  },
  {
    "text": "we need iron discipline",
    "y2016": false,
    "need": true,
    "matters": false,
    "fact": true,
    "command": false,
    "I": false,
    "We": true,
    "You": false,
    "3rdPersonSingular": false,
    "business": false,
    "politics": false,
    "popCulture": false,
    "scienceTech": false,
    "religion": false,
    "education": false,
    "global": false,
    "community": false,
    "personal": false,
    "fashion": false,
    "military": false
  },
  {
    "text": "we need tax reform",
    "y2016": false,
    "need": false,
    "matters": false,
    "fact": true,
    "command": false,
    "I": false,
    "We": true,
    "You": false,
    "3rdPersonSingular": false,
    "business": false,
    "politics": true,
    "popCulture": false,
    "scienceTech": false,
    "religion": false,
    "education": false,
    "global": true,
    "community": false,
    "personal": false,
    "fashion": false,
    "military": false
  },
  {
    "text": "comprehensive immigration reform is needed",
    "y2016": false,
    "need": true,
    "matters": false,
    "fact": true,
    "command": false,
    "I": false,
    "We": false,
    "You": false,
    "3rdPersonSingular": false,
    "business": false,
    "politics": true,
    "popCulture": false,
    "scienceTech": false,
    "religion": false,
    "education": false,
    "global": true,
    "community": false,
    "personal": false,
    "fashion": false,
    "military": false
  },
  {
    "text": "a safe and effective HIV vaccine is needed",
    "y2016": false,
    "need": true,
    "matters": false,
    "fact": true,
    "command": false,
    "I": false,
    "We": false,
    "You": false,
    "3rdPersonSingular": false,
    "business": false,
    "politics": false,
    "popCulture": false,
    "scienceTech": true,
    "religion": false,
    "education": false,
    "global": false,
    "community": false,
    "personal": false,
    "fashion": false,
    "military": false
  },
  {
    "text": "understanding the continuities of long-standing narratives and stereotypes about Haitians and their meaning matter",
    "y2016": false,
    "need": false,
    "matters": true,
    "fact": true,
    "command": false,
    "I": false,
    "We": false,
    "You": false,
    "3rdPersonSingular": false,
    "business": false,
    "politics": false,
    "popCulture": false,
    "scienceTech": false,
    "religion": false,
    "education": true,
    "global": false,
    "community": true,
    "personal": false,
    "fashion": false,
    "military": false
  },
  {
    "text": "she needed her mom",
    "y2016": false,
    "need": true,
    "matters": false,
    "fact": true,
    "command": false,
    "I": false,
    "We": false,
    "You": false,
    "3rdPersonSingular": true,
    "business": false,
    "politics": false,
    "popCulture": false,
    "scienceTech": false,
    "religion": false,
    "education": false,
    "global": false,
    "community": false,
    "personal": true,
    "fashion": false,
    "military": false
  },
  {
    "text": "I need you by my side",
    "y2016": false,
    "need": true,
    "matters": false,
    "fact": true,
    "command": false,
    "I": true,
    "We": false,
    "You": true,
    "3rdPersonSingular": false,
    "business": false,
    "politics": false,
    "popCulture": false,
    "scienceTech": false,
    "religion": false,
    "education": false,
    "global": false,
    "community": false,
    "personal": true,
    "fashion": false,
    "military": false
  },
  {
    "text": "the key to the future is, paradoxically, the past",
    "y2016": false,
    "need": false,
    "matters": false,
    "fact": true,
    "command": false,
    "I": false,
    "We": false,
    "You": false,
    "3rdPersonSingular": false,
    "business": false,
    "politics": false,
    "popCulture": false,
    "scienceTech": false,
    "religion": false,
    "education": false,
    "global": true,
    "community": false,
    "personal": false,
    "fashion": false,
    "military": false
  },
  {
    "text": "women have additional expectations of themselves",
    "y2016": false,
    "need": false,
    "matters": false,
    "fact": true,
    "command": false,
    "I": false,
    "We": false,
    "You": false,
    "3rdPersonSingular": false,
    "business": false,
    "politics": false,
    "popCulture": false,
    "scienceTech": false,
    "religion": false,
    "education": false,
    "global": false,
    "community": true,
    "personal": true,
    "fashion": false,
    "military": false
  },
  {
    "text": "every working woman in this country needs every cent she can get",
    "y2016": false,
    "need": true,
    "matters": false,
    "fact": true,
    "command": false,
    "I": false,
    "We": false,
    "You": false,
    "3rdPersonSingular": false,
    "business": false,
    "politics": false,
    "popCulture": false,
    "scienceTech": false,
    "religion": false,
    "education": false,
    "global": true,
    "community": true,
    "personal": false,
    "fashion": false,
    "military": false
  },
  {
    "text": "we need wise and deep-hearted men to hold the crook and women and men of conviction to make formal pledges of lifelong service to the church's many vital ministries",
    "y2016": false,
    "need": true,
    "matters": false,
    "fact": false,
    "command": true,
    "I": false,
    "We": true,
    "You": false,
    "3rdPersonSingular": false,
    "business": false,
    "politics": false,
    "popCulture": false,
    "scienceTech": false,
    "religion": true,
    "education": false,
    "global": false,
    "community": true,
    "personal": false,
    "fashion": false,
    "military": false
  },
  {
    "text": "the active engagement of the American people in their democracy is needed",
    "y2016": false,
    "need": true,
    "matters": false,
    "fact": true,
    "command": false,
    "I": false,
    "We": false,
    "You": false,
    "3rdPersonSingular": false,
    "business": false,
    "politics": true,
    "popCulture": false,
    "scienceTech": false,
    "religion": false,
    "education": false,
    "global": true,
    "community": true,
    "personal": false,
    "fashion": false,
    "military": false
  },
  {
    "text": "experienced boaters demand economy and performance",
    "y2016": false,
    "need": false,
    "matters": false,
    "fact": false,
    "command": true,
    "I": false,
    "We": false,
    "You": false,
    "3rdPersonSingular": false,
    "business": false,
    "politics": false,
    "popCulture": false,
    "scienceTech": true,
    "religion": false,
    "education": false,
    "global": false,
    "community": true,
    "personal": false,
    "fashion": false,
    "military": false
  },
  {
    "text": "she is redefining what it means to indulge",
    "y2016": false,
    "need": false,
    "matters": false,
    "fact": true,
    "command": false,
    "I": false,
    "We": false,
    "You": false,
    "3rdPersonSingular": true,
    "business": false,
    "politics": false,
    "popCulture": true,
    "scienceTech": false,
    "religion": false,
    "education": false,
    "global": false,
    "community": false,
    "personal": true,
    "fashion": false,
    "military": false
  },
  {
    "text": "American ballet, artistically speaking, is a homogeneous entity",
    "y2016": false,
    "need": false,
    "matters": false,
    "fact": true,
    "command": false,
    "I": false,
    "We": false,
    "You": false,
    "3rdPersonSingular": false,
    "business": false,
    "politics": false,
    "popCulture": true,
    "scienceTech": false,
    "religion": false,
    "education": false,
    "global": false,
    "community": true,
    "personal": false,
    "fashion": false,
    "military": false
  },
  {
    "text": "Wall Street is still the place to be perhaps",
    "y2016": false,
    "need": false,
    "matters": false,
    "fact": true,
    "command": false,
    "I": false,
    "We": false,
    "You": false,
    "3rdPersonSingular": false,
    "business": true,
    "politics": false,
    "popCulture": false,
    "scienceTech": false,
    "religion": false,
    "education": false,
    "global": false,
    "community": false,
    "personal": false,
    "fashion": false,
    "military": false
  },
  {
    "text": "we need you to surround people you love with positive energy",
    "y2016": false,
    "need": false,
    "matters": false,
    "fact": false,
    "command": true,
    "I": false,
    "We": true,
    "You": true,
    "3rdPersonSingular": false,
    "business": false,
    "politics": false,
    "popCulture": false,
    "scienceTech": false,
    "religion": false,
    "education": false,
    "global": false,
    "community": true,
    "personal": true,
    "fashion": false,
    "military": false
  },
  {
    "text": "Europeans are clinging to their day of rest",
    "y2016": false,
    "need": false,
    "matters": false,
    "fact": true,
    "command": false,
    "I": false,
    "We": false,
    "You": false,
    "3rdPersonSingular": false,
    "business": true,
    "politics": false,
    "popCulture": false,
    "scienceTech": false,
    "religion": false,
    "education": false,
    "global": false,
    "community": false,
    "personal": false,
    "fashion": false,
    "military": false
  },
  {
    "text": "fans appreciate having a choice",
    "y2016": false,
    "need": false,
    "matters": false,
    "fact": true,
    "command": false,
    "I": false,
    "We": false,
    "You": false,
    "3rdPersonSingular": false,
    "business": false,
    "politics": false,
    "popCulture": true,
    "scienceTech": false,
    "religion": false,
    "education": false,
    "global": false,
    "community": true,
    "personal": false,
    "fashion": false,
    "military": false
  },
  {
    "text": "making effective policy to cope with an increasingly complex and interconnected world requires integrating varied dimensions -- defense and diplomacy, finance and trade, the environment and homeland security, science and social policy -- into a coherent foreign policy",
    "y2016": false,
    "need": false,
    "matters": false,
    "fact": true,
    "command": false,
    "I": false,
    "We": false,
    "You": false,
    "3rdPersonSingular": false,
    "business": false,
    "politics": true,
    "popCulture": false,
    "scienceTech": true,
    "religion": false,
    "education": false,
    "global": true,
    "community": false,
    "personal": false,
    "fashion": false,
    "military": false
  },
  {
    "text": "we, as parents, must be aware of the importance of braille to children who are blind or visually impaired",
    "y2016": false,
    "need": false,
    "matters": false,
    "fact": true,
    "command": false,
    "I": false,
    "We": true,
    "You": false,
    "3rdPersonSingular": false,
    "business": false,
    "politics": false,
    "popCulture": false,
    "scienceTech": false,
    "religion": false,
    "education": true,
    "global": false,
    "community": true,
    "personal": true,
    "fashion": false,
    "military": false
  },
  {
    "text": "it is likely that clients, especially in-house counsel, will give a chilly response to rate hikes and scrutinize what they are getting for that rate",
    "y2016": false,
    "need": false,
    "matters": false,
    "fact": true,
    "command": false,
    "I": false,
    "We": false,
    "You": false,
    "3rdPersonSingular": false,
    "business": true,
    "politics": false,
    "popCulture": false,
    "scienceTech": false,
    "religion": false,
    "education": false,
    "global": false,
    "community": false,
    "personal": false,
    "fashion": false,
    "military": false
  },
  {
    "text": "attorneys anxious about billable requirements, maintain the same enthusiasm you had that first day of work (or at least the appearance of it)",
    "y2016": false,
    "need": false,
    "matters": false,
    "fact": false,
    "command": true,
    "I": false,
    "We": false,
    "You": false,
    "3rdPersonSingular": false,
    "business": true,
    "politics": false,
    "popCulture": false,
    "scienceTech": false,
    "religion": false,
    "education": false,
    "global": false,
    "community": false,
    "personal": true,
    "fashion": false,
    "military": false
  },
  {
    "text": "we need glamour and beauty",
    "y2016": false,
    "need": true,
    "matters": false,
    "fact": true,
    "command": false,
    "I": false,
    "We": true,
    "You": false,
    "3rdPersonSingular": false,
    "business": false,
    "politics": false,
    "popCulture": true,
    "scienceTech": false,
    "religion": false,
    "education": false,
    "global": false,
    "community": false,
    "personal": false,
    "fashion": true,
    "military": false
  },
  {
    "text": "many people are reading about the founding of our country",
    "y2016": false,
    "need": false,
    "matters": false,
    "fact": true,
    "command": false,
    "I": false,
    "We": false,
    "You": false,
    "3rdPersonSingular": false,
    "business": false,
    "politics": false,
    "popCulture": false,
    "scienceTech": false,
    "religion": false,
    "education": true,
    "global": true,
    "community": true,
    "personal": false,
    "fashion": false,
    "military": false
  },
  {
    "text": "Special forces teams are at the tip of the spear",
    "y2016": false,
    "need": false,
    "matters": false,
    "fact": true,
    "command": false,
    "I": false,
    "We": false,
    "You": false,
    "3rdPersonSingular": false,
    "business": false,
    "politics": true,
    "popCulture": false,
    "scienceTech": false,
    "religion": false,
    "education": false,
    "global": false,
    "community": false,
    "personal": false,
    "fashion": false,
    "military": true
  },
  {
    "text": "I need you by my side",
    "y2016": false,
    "need": true,
    "matters": false,
    "fact": true,
    "command": false,
    "I": true,
    "We": false,
    "You": true,
    "3rdPersonSingular": false,
    "business": false,
    "politics": false,
    "popCulture": false,
    "scienceTech": false,
    "religion": false,
    "education": false,
    "global": false,
    "community": false,
    "personal": true,
    "fashion": false,
    "military": false
  },
  {
    "text": "people just really have this appetite for fashion",
    "y2016": false,
    "need": false,
    "matters": false,
    "fact": true,
    "command": false,
    "I": false,
    "We": false,
    "You": false,
    "3rdPersonSingular": false,
    "business": false,
    "politics": false,
    "popCulture": true,
    "scienceTech": false,
    "religion": false,
    "education": false,
    "global": false,
    "community": false,
    "personal": true,
    "fashion": true,
    "military": false
  },
  {
    "text": "our country is in need of leadership on a host of urgent environmental challenges that face our communities, our cities, our farms, and our rivers, streams, lakes, and oceans",
    "y2016": false,
    "need": true,
    "matters": false,
    "fact": true,
    "command": false,
    "I": false,
    "We": true,
    "You": false,
    "3rdPersonSingular": false,
    "business": false,
    "politics": true,
    "popCulture": false,
    "scienceTech": true,
    "religion": false,
    "education": false,
    "global": true,
    "community": false,
    "personal": false,
    "fashion": false,
    "military": false
  },
  {
    "text": "I want to learn about this magnetic disturbance",
    "y2016": false,
    "need": false,
    "matters": false,
    "fact": true,
    "command": false,
    "I": true,
    "We": false,
    "You": false,
    "3rdPersonSingular": false,
    "business": false,
    "politics": false,
    "popCulture": false,
    "scienceTech": true,
    "religion": false,
    "education": false,
    "global": false,
    "community": false,
    "personal": true,
    "fashion": false,
    "military": false
  },
  {
    "text": "the outcome Vanessa was talking about was 100 percent unacceptable",
    "y2016": false,
    "need": false,
    "matters": false,
    "fact": true,
    "command": false,
    "I": false,
    "We": false,
    "You": false,
    "3rdPersonSingular": true,
    "business": false,
    "politics": false,
    "popCulture": false,
    "scienceTech": false,
    "religion": false,
    "education": false,
    "global": false,
    "community": false,
    "personal": true,
    "fashion": false,
    "military": false
  },
  {
    "text": "consumers are pampering their pets with high-end toys, treats, grooming products and accessories",
    "y2016": false,
    "need": false,
    "matters": false,
    "fact": true,
    "command": false,
    "I": false,
    "We": false,
    "You": false,
    "3rdPersonSingular": false,
    "business": true,
    "politics": false,
    "popCulture": true,
    "scienceTech": false,
    "religion": false,
    "education": false,
    "global": true,
    "community": false,
    "personal": false,
    "fashion": false,
    "military": false
  },
  {
    "text": "people need to feel excited about their clothes",
    "y2016": false,
    "need": false,
    "matters": false,
    "fact": false,
    "command": true,
    "I": false,
    "We": false,
    "You": false,
    "3rdPersonSingular": false,
    "business": false,
    "politics": false,
    "popCulture": true,
    "scienceTech": false,
    "religion": false,
    "education": false,
    "global": false,
    "community": false,
    "personal": false,
    "fashion": true,
    "military": false
  },
  {
    "text": "fashion has a role to play",
    "y2016": false,
    "need": false,
    "matters": false,
    "fact": true,
    "command": false,
    "I": false,
    "We": false,
    "You": false,
    "3rdPersonSingular": false,
    "business": false,
    "politics": false,
    "popCulture": true,
    "scienceTech": false,
    "religion": false,
    "education": false,
    "global": false,
    "community": false,
    "personal": true,
    "fashion": true,
    "military": false
  },
  {
    "text": "Atlanta is also a great place for the kids",
    "y2016": false,
    "need": false,
    "matters": false,
    "fact": true,
    "command": false,
    "I": false,
    "We": false,
    "You": false,
    "3rdPersonSingular": false,
    "business": false,
    "politics": false,
    "popCulture": true,
    "scienceTech": false,
    "religion": false,
    "education": false,
    "global": false,
    "community": true,
    "personal": false,
    "fashion": false,
    "military": false
  },
  {
    "text": "I know that life comes at us in ways we can't predict or control",
    "y2016": false,
    "need": false,
    "matters": false,
    "fact": true,
    "command": false,
    "I": true,
    "We": true,
    "You": false,
    "3rdPersonSingular": false,
    "business": false,
    "politics": false,
    "popCulture": false,
    "scienceTech": false,
    "religion": false,
    "education": false,
    "global": false,
    "community": true,
    "personal": false,
    "fashion": false,
    "military": false
  },
  {
    "text": "viewers need The Martha Stewart Show",
    "y2016": false,
    "need": true,
    "matters": false,
    "fact": true,
    "command": false,
    "I": false,
    "We": false,
    "You": false,
    "3rdPersonSingular": false,
    "business": false,
    "politics": false,
    "popCulture": true,
    "scienceTech": false,
    "religion": false,
    "education": false,
    "global": false,
    "community": false,
    "personal": false,
    "fashion": true,
    "military": false
  },
  {
    "text": "Bob Dylan knows the caprices of the world he lives in",
    "y2016": false,
    "need": false,
    "matters": false,
    "fact": true,
    "command": false,
    "I": false,
    "We": false,
    "You": false,
    "3rdPersonSingular": true,
    "business": false,
    "politics": false,
    "popCulture": false,
    "scienceTech": false,
    "religion": false,
    "education": false,
    "global": false,
    "community": false,
    "personal": true,
    "fashion": false,
    "military": false
  },
  {
    "text": "people need to make sure they are diversified broadly in the U.S. and global markets",
    "y2016": false,
    "need": false,
    "matters": false,
    "fact": false,
    "command": true,
    "I": false,
    "We": false,
    "You": false,
    "3rdPersonSingular": false,
    "business": true,
    "politics": false,
    "popCulture": false,
    "scienceTech": false,
    "religion": false,
    "education": false,
    "global": true,
    "community": false,
    "personal": false,
    "fashion": false,
    "military": false
  },
  {
    "text": "I might be butting heads with both jobs",
    "y2016": false,
    "need": false,
    "matters": false,
    "fact": true,
    "command": false,
    "I": true,
    "We": false,
    "You": false,
    "3rdPersonSingular": false,
    "business": false,
    "politics": false,
    "popCulture": false,
    "scienceTech": false,
    "religion": false,
    "education": false,
    "global": false,
    "community": false,
    "personal": true,
    "fashion": false,
    "military": false
  },
  {
    "text": "her comments and opinions are much more important to me",
    "y2016": false,
    "need": false,
    "matters": false,
    "fact": true,
    "command": false,
    "I": false,
    "We": false,
    "You": false,
    "3rdPersonSingular": true,
    "business": false,
    "politics": false,
    "popCulture": false,
    "scienceTech": false,
    "religion": false,
    "education": false,
    "global": false,
    "community": false,
    "personal": true,
    "fashion": false,
    "military": false
  },
  {
    "text": "homeowners will need consumer protection for new home construction or remodeling",
    "y2016": false,
    "need": true,
    "matters": false,
    "fact": true,
    "command": false,
    "I": false,
    "We": false,
    "You": false,
    "3rdPersonSingular": false,
    "business": true,
    "politics": false,
    "popCulture": false,
    "scienceTech": false,
    "religion": false,
    "education": false,
    "global": false,
    "community": false,
    "personal": false,
    "fashion": false,
    "military": false
  },
  {
    "text": "we are in this together",
    "y2016": false,
    "need": false,
    "matters": false,
    "fact": true,
    "command": false,
    "I": false,
    "We": true,
    "You": false,
    "3rdPersonSingular": false,
    "business": false,
    "politics": false,
    "popCulture": false,
    "scienceTech": false,
    "religion": false,
    "education": false,
    "global": false,
    "community": false,
    "personal": true,
    "fashion": false,
    "military": false
  },
  {
    "text": "we are sensitive to the economic times",
    "y2016": false,
    "need": false,
    "matters": false,
    "fact": true,
    "command": false,
    "I": false,
    "We": true,
    "You": false,
    "3rdPersonSingular": false,
    "business": true,
    "politics": true,
    "popCulture": false,
    "scienceTech": false,
    "religion": false,
    "education": false,
    "global": true,
    "community": false,
    "personal": false,
    "fashion": false,
    "military": false
  },
  {
    "text": "education and social security are crucial",
    "y2016": false,
    "need": false,
    "matters": false,
    "fact": true,
    "command": false,
    "I": false,
    "We": false,
    "You": false,
    "3rdPersonSingular": false,
    "business": false,
    "politics": true,
    "popCulture": false,
    "scienceTech": false,
    "religion": false,
    "education": true,
    "global": true,
    "community": true,
    "personal": false,
    "fashion": false,
    "military": false
  },
  {
    "text": "the relationship between professional school counselors and principals is crucial",
    "y2016": false,
    "need": false,
    "matters": false,
    "fact": true,
    "command": false,
    "I": false,
    "We": false,
    "You": false,
    "3rdPersonSingular": false,
    "business": false,
    "politics": false,
    "popCulture": false,
    "scienceTech": false,
    "religion": false,
    "education": true,
    "global": false,
    "community": true,
    "personal": false,
    "fashion": false,
    "military": false
  },
  {
    "text": "the responsibilities assigned to regulatory agencies are expanding and standards for privacy and confidentiality change continually",
    "y2016": false,
    "need": false,
    "matters": false,
    "fact": true,
    "command": false,
    "I": false,
    "We": false,
    "You": false,
    "3rdPersonSingular": false,
    "business": true,
    "politics": true,
    "popCulture": false,
    "scienceTech": true,
    "religion": false,
    "education": false,
    "global": false,
    "community": false,
    "personal": false,
    "fashion": false,
    "military": false
  },
  {
    "text": "he needed the help of his few friends that he could rely on",
    "y2016": false,
    "need": true,
    "matters": false,
    "fact": true,
    "command": false,
    "I": false,
    "We": false,
    "You": false,
    "3rdPersonSingular": true,
    "business": false,
    "politics": false,
    "popCulture": false,
    "scienceTech": false,
    "religion": false,
    "education": false,
    "global": false,
    "community": false,
    "personal": true,
    "fashion": false,
    "military": false
  },
  {
    "text": "the most important thing is to embody a trend that works for you and not blindly follow the themes of the moment",
    "y2016": false,
    "need": false,
    "matters": false,
    "fact": false,
    "command": true,
    "I": false,
    "We": false,
    "You": true,
    "3rdPersonSingular": false,
    "business": false,
    "politics": false,
    "popCulture": true,
    "scienceTech": false,
    "religion": false,
    "education": false,
    "global": false,
    "community": false,
    "personal": true,
    "fashion": true,
    "military": false
  },
  {
    "text": "cool' is a moving target",
    "y2016": false,
    "need": false,
    "matters": false,
    "fact": true,
    "command": false,
    "I": false,
    "We": false,
    "You": false,
    "3rdPersonSingular": false,
    "business": false,
    "politics": false,
    "popCulture": true,
    "scienceTech": false,
    "religion": false,
    "education": false,
    "global": false,
    "community": false,
    "personal": false,
    "fashion": true,
    "military": true
  },
  {
    "text": "I'm able to live in the present",
    "y2016": false,
    "need": false,
    "matters": false,
    "fact": true,
    "command": false,
    "I": true,
    "We": false,
    "You": false,
    "3rdPersonSingular": false,
    "business": false,
    "politics": false,
    "popCulture": false,
    "scienceTech": false,
    "religion": false,
    "education": false,
    "global": false,
    "community": false,
    "personal": true,
    "fashion": false,
    "military": false
  },
  {
    "text": "quality of life matters, perhaps",
    "y2016": false,
    "need": false,
    "matters": true,
    "fact": true,
    "command": false,
    "I": false,
    "We": false,
    "You": false,
    "3rdPersonSingular": false,
    "business": false,
    "politics": false,
    "popCulture": false,
    "scienceTech": false,
    "religion": false,
    "education": false,
    "global": true,
    "community": false,
    "personal": false,
    "fashion": false,
    "military": false
  },
  {
    "text": "perhaps we need the priesthood of professional storytelling",
    "y2016": false,
    "need": true,
    "matters": false,
    "fact": true,
    "command": false,
    "I": false,
    "We": true,
    "You": false,
    "3rdPersonSingular": false,
    "business": false,
    "politics": false,
    "popCulture": false,
    "scienceTech": false,
    "religion": true,
    "education": false,
    "global": false,
    "community": true,
    "personal": false,
    "fashion": false,
    "military": false
  },
  {
    "text": "our customers can enjoy a straightforward mobile working experience with fast access to e-mail and business applications.",
    "y2016": false,
    "need": false,
    "matters": false,
    "fact": true,
    "command": false,
    "I": false,
    "We": true,
    "You": false,
    "3rdPersonSingular": false,
    "business": true,
    "politics": false,
    "popCulture": false,
    "scienceTech": false,
    "religion": false,
    "education": false,
    "global": false,
    "community": false,
    "personal": false,
    "fashion": false,
    "military": false
  },
  {
    "text": "the studios keep clamoring for more",
    "y2016": false,
    "need": false,
    "matters": false,
    "fact": true,
    "command": false,
    "I": false,
    "We": false,
    "You": false,
    "3rdPersonSingular": false,
    "business": true,
    "politics": false,
    "popCulture": true,
    "scienceTech": false,
    "religion": false,
    "education": false,
    "global": false,
    "community": false,
    "personal": false,
    "fashion": false,
    "military": false
  },
  {
    "text": "science is needed",
    "y2016": false,
    "need": true,
    "matters": false,
    "fact": true,
    "command": false,
    "I": false,
    "We": false,
    "You": false,
    "3rdPersonSingular": false,
    "business": false,
    "politics": false,
    "popCulture": false,
    "scienceTech": true,
    "religion": false,
    "education": true,
    "global": false,
    "community": false,
    "personal": false,
    "fashion": false,
    "military": false
  },
  {
    "text": "supervisors are faced with directing and supervising practicum and internship experiences with counseling interns who are effectively using Play Therapy, trying to use Play Therapy, or struggling to counsel children using traditional and often inappropriate, adult-therapy techniques",
    "y2016": false,
    "need": false,
    "matters": false,
    "fact": true,
    "command": false,
    "I": false,
    "We": false,
    "You": false,
    "3rdPersonSingular": false,
    "business": true,
    "politics": false,
    "popCulture": false,
    "scienceTech": false,
    "religion": false,
    "education": true,
    "global": false,
    "community": false,
    "personal": false,
    "fashion": false,
    "military": false
  },
  {
    "text": "U.S. boots on the ground in Iraq may be needed",
    "y2016": false,
    "need": true,
    "matters": false,
    "fact": true,
    "command": false,
    "I": false,
    "We": false,
    "You": false,
    "3rdPersonSingular": false,
    "business": false,
    "politics": true,
    "popCulture": false,
    "scienceTech": false,
    "religion": false,
    "education": false,
    "global": true,
    "community": false,
    "personal": false,
    "fashion": false,
    "military": true
  },
  {
    "text": "the mantra of the Navy is a commitment to help fitness",
    "y2016": false,
    "need": false,
    "matters": false,
    "fact": true,
    "command": false,
    "I": false,
    "We": false,
    "You": false,
    "3rdPersonSingular": false,
    "business": false,
    "politics": true,
    "popCulture": false,
    "scienceTech": false,
    "religion": false,
    "education": false,
    "global": false,
    "community": true,
    "personal": false,
    "fashion": true,
    "military": true
  },
  {
    "text": "getting through, especially to girls, is critical",
    "y2016": false,
    "need": false,
    "matters": false,
    "fact": true,
    "command": false,
    "I": false,
    "We": false,
    "You": false,
    "3rdPersonSingular": false,
    "business": false,
    "politics": false,
    "popCulture": false,
    "scienceTech": false,
    "religion": false,
    "education": true,
    "global": false,
    "community": false,
    "personal": false,
    "fashion": false,
    "military": false
  },
  {
    "text": "studio heads are on the look-out for bargains",
    "y2016": false,
    "need": false,
    "matters": false,
    "fact": true,
    "command": false,
    "I": false,
    "We": false,
    "You": false,
    "3rdPersonSingular": false,
    "business": false,
    "politics": false,
    "popCulture": true,
    "scienceTech": false,
    "religion": false,
    "education": false,
    "global": false,
    "community": false,
    "personal": false,
    "fashion": false,
    "military": false
  },
  {
    "text": "people need to be empowered and encouraged",
    "y2016": false,
    "need": false,
    "matters": false,
    "fact": false,
    "command": true,
    "I": false,
    "We": false,
    "You": false,
    "3rdPersonSingular": false,
    "business": false,
    "politics": false,
    "popCulture": false,
    "scienceTech": false,
    "religion": false,
    "education": false,
    "global": false,
    "community": false,
    "personal": true,
    "fashion": false,
    "military": false
  },
  {
    "text": "he wanted to cover that distance toward the mountains where he felt sure he could elude any number of pursuers",
    "y2016": false,
    "need": false,
    "matters": false,
    "fact": true,
    "command": false,
    "I": false,
    "We": false,
    "You": false,
    "3rdPersonSingular": true,
    "business": false,
    "politics": false,
    "popCulture": false,
    "scienceTech": false,
    "religion": false,
    "education": false,
    "global": false,
    "community": false,
    "personal": true,
    "fashion": false,
    "military": false
  },
  {
    "text": "I need this job",
    "y2016": false,
    "need": true,
    "matters": false,
    "fact": true,
    "command": false,
    "I": true,
    "We": false,
    "You": false,
    "3rdPersonSingular": false,
    "business": true,
    "politics": false,
    "popCulture": false,
    "scienceTech": false,
    "religion": false,
    "education": false,
    "global": false,
    "community": false,
    "personal": true,
    "fashion": false,
    "military": false
  },
  {
    "text": "the job of an aircraft needs doing",
    "y2016": false,
    "need": true,
    "matters": false,
    "fact": true,
    "command": false,
    "I": false,
    "We": false,
    "You": false,
    "3rdPersonSingular": false,
    "business": true,
    "politics": false,
    "popCulture": false,
    "scienceTech": false,
    "religion": false,
    "education": false,
    "global": true,
    "community": false,
    "personal": false,
    "fashion": false,
    "military": true
  },
  {
    "text": "Pennsylvania keeps alive the memory of both Civil Wars, the war of the famous captains and the people whose stories are just beginning to be told, in unspoiled country-side, historic villages, and of course the brilliantly preserved battlefield itself",
    "y2016": false,
    "need": false,
    "matters": false,
    "fact": true,
    "command": false,
    "I": false,
    "We": false,
    "You": false,
    "3rdPersonSingular": false,
    "business": false,
    "politics": false,
    "popCulture": false,
    "scienceTech": false,
    "religion": false,
    "education": false,
    "global": true,
    "community": true,
    "personal": false,
    "fashion": false,
    "military": false
  },
  {
    "text": "the nation needs Iraqi professionals' experience and expertise",
    "y2016": false,
    "need": true,
    "matters": false,
    "fact": true,
    "command": false,
    "I": false,
    "We": false,
    "You": false,
    "3rdPersonSingular": false,
    "business": false,
    "politics": true,
    "popCulture": false,
    "scienceTech": false,
    "religion": false,
    "education": false,
    "global": true,
    "community": false,
    "personal": false,
    "fashion": false,
    "military": false
  },
  {
    "text": "success in Mexico depends on having the right parents rather than on effort and merit",
    "y2016": false,
    "need": false,
    "matters": false,
    "fact": true,
    "command": false,
    "I": false,
    "We": false,
    "You": false,
    "3rdPersonSingular": false,
    "business": false,
    "politics": true,
    "popCulture": false,
    "scienceTech": false,
    "religion": false,
    "education": false,
    "global": true,
    "community": false,
    "personal": false,
    "fashion": false,
    "military": false
  },
  {
    "text": "there is an imbalance not only of wealth but of opportunities kept in place by the rich and the powerful",
    "y2016": false,
    "need": false,
    "matters": false,
    "fact": true,
    "command": false,
    "I": false,
    "We": false,
    "You": false,
    "3rdPersonSingular": false,
    "business": false,
    "politics": true,
    "popCulture": false,
    "scienceTech": false,
    "religion": false,
    "education": false,
    "global": false,
    "community": true,
    "personal": false,
    "fashion": false,
    "military": false
  },
  {
    "text": "the US government needs China as well",
    "y2016": false,
    "need": true,
    "matters": false,
    "fact": true,
    "command": false,
    "I": false,
    "We": false,
    "You": false,
    "3rdPersonSingular": false,
    "business": true,
    "politics": true,
    "popCulture": false,
    "scienceTech": false,
    "religion": false,
    "education": false,
    "global": true,
    "community": false,
    "personal": false,
    "fashion": false,
    "military": true
  },
  {
    "text": "Americans are sick of the religious right",
    "y2016": false,
    "need": false,
    "matters": false,
    "fact": true,
    "command": false,
    "I": false,
    "We": false,
    "You": false,
    "3rdPersonSingular": false,
    "business": false,
    "politics": true,
    "popCulture": false,
    "scienceTech": false,
    "religion": true,
    "education": false,
    "global": false,
    "community": false,
    "personal": false,
    "fashion": false,
    "military": false
  },
  {
    "text": "Dick is incapable of liking anything",
    "y2016": false,
    "need": false,
    "matters": false,
    "fact": true,
    "command": false,
    "I": false,
    "We": false,
    "You": false,
    "3rdPersonSingular": true,
    "business": false,
    "politics": false,
    "popCulture": false,
    "scienceTech": false,
    "religion": false,
    "education": false,
    "global": false,
    "community": false,
    "personal": true,
    "fashion": false,
    "military": false
  },
  {
    "text": "we can find fresh, healthy foods nearly anywhere at any time of year",
    "y2016": false,
    "need": false,
    "matters": false,
    "fact": true,
    "command": false,
    "I": false,
    "We": false,
    "You": false,
    "3rdPersonSingular": false,
    "business": false,
    "politics": false,
    "popCulture": false,
    "scienceTech": false,
    "religion": false,
    "education": false,
    "global": true,
    "community": false,
    "personal": false,
    "fashion": false,
    "military": false
  },
  {
    "text": "letting your personal style shine through is key",
    "y2016": false,
    "need": false,
    "matters": false,
    "fact": true,
    "command": false,
    "I": false,
    "We": false,
    "You": false,
    "3rdPersonSingular": false,
    "business": false,
    "politics": false,
    "popCulture": true,
    "scienceTech": false,
    "religion": false,
    "education": false,
    "global": false,
    "community": false,
    "personal": true,
    "fashion": true,
    "military": false
  },
  {
    "text": "the sports world is looking to statistics for performance-enhancing insight",
    "y2016": false,
    "need": false,
    "matters": false,
    "fact": true,
    "command": false,
    "I": false,
    "We": false,
    "You": false,
    "3rdPersonSingular": false,
    "business": false,
    "politics": false,
    "popCulture": true,
    "scienceTech": true,
    "religion": false,
    "education": false,
    "global": false,
    "community": false,
    "personal": false,
    "fashion": false,
    "military": false
  },
  {
    "text": "we must rely on the courts",
    "y2016": false,
    "need": false,
    "matters": false,
    "fact": false,
    "command": true,
    "I": false,
    "We": false,
    "You": false,
    "3rdPersonSingular": false,
    "business": false,
    "politics": true,
    "popCulture": false,
    "scienceTech": false,
    "religion": false,
    "education": false,
    "global": true,
    "community": false,
    "personal": false,
    "fashion": false,
    "military": false
  },
  {
    "text": "mantle plumes indeed exist",
    "y2016": false,
    "need": false,
    "matters": false,
    "fact": false,
    "command": false,
    "I": false,
    "We": false,
    "You": false,
    "3rdPersonSingular": false,
    "business": false,
    "politics": false,
    "popCulture": false,
    "scienceTech": true,
    "religion": false,
    "education": false,
    "global": true,
    "community": false,
    "personal": false,
    "fashion": false,
    "military": false
  },
  {
    "text": "people want to know about their heritage",
    "y2016": false,
    "need": false,
    "matters": false,
    "fact": false,
    "command": false,
    "I": false,
    "We": false,
    "You": false,
    "3rdPersonSingular": false,
    "business": false,
    "politics": false,
    "popCulture": false,
    "scienceTech": false,
    "religion": false,
    "education": false,
    "global": false,
    "community": true,
    "personal": true,
    "fashion": false,
    "military": false
  },
  {
    "text": "borrowers need to focus on educating themselves",
    "y2016": false,
    "need": false,
    "matters": false,
    "fact": false,
    "command": false,
    "I": false,
    "We": false,
    "You": false,
    "3rdPersonSingular": false,
    "business": true,
    "politics": false,
    "popCulture": false,
    "scienceTech": false,
    "religion": false,
    "education": true,
    "global": false,
    "community": false,
    "personal": false,
    "fashion": false,
    "military": false
  },
  {
    "text": "adults, too, are a part of the Technological Diaspora",
    "y2016": false,
    "need": false,
    "matters": false,
    "fact": false,
    "command": false,
    "I": false,
    "We": false,
    "You": false,
    "3rdPersonSingular": false,
    "business": false,
    "politics": false,
    "popCulture": false,
    "scienceTech": true,
    "religion": false,
    "education": false,
    "global": false,
    "community": false,
    "personal": false,
    "fashion": false,
    "military": false
  },
  {
    "text": "we need people who think broadly and who understand systems, connections, patterns, and root causes",
    "y2016": false,
    "need": true,
    "matters": false,
    "fact": false,
    "command": false,
    "I": false,
    "We": false,
    "You": false,
    "3rdPersonSingular": false,
    "business": true,
    "politics": false,
    "popCulture": false,
    "scienceTech": true,
    "religion": false,
    "education": true,
    "global": true,
    "community": false,
    "personal": false,
    "fashion": false,
    "military": false
  },
  {
    "text": "we need to listen to Tony Blair",
    "y2016": true,
    "need": true,
    "matters": false,
    "fact": false,
    "command": false,
    "I": false,
    "We": true,
    "You": false,
    "3rdPersonSingular": false,
    "business": true,
    "politics": true,
    "popCulture": false,
    "scienceTech": false,
    "religion": false,
    "education": false,
    "global": true,
    "community": false,
    "personal": false,
    "fashion": false,
    "military": false
  },
  {
    "text": "designers must transform America",
    "y2016": true,
    "need": false,
    "matters": false,
    "fact": false,
    "command": true,
    "I": false,
    "We": false,
    "You": false,
    "3rdPersonSingular": false,
    "business": true,
    "politics": false,
    "popCulture": false,
    "scienceTech": true,
    "religion": false,
    "education": false,
    "global": true,
    "community": false,
    "personal": false,
    "fashion": false,
    "military": false
  },
  {
    "text": "Kamala Khan is the superhero we need",
    "y2016": true,
    "need": true,
    "matters": false,
    "fact": false,
    "command": false,
    "I": false,
    "We": false,
    "You": false,
    "3rdPersonSingular": true,
    "business": false,
    "politics": false,
    "popCulture": true,
    "scienceTech": false,
    "religion": false,
    "education": false,
    "global": false,
    "community": false,
    "personal": false,
    "fashion": false,
    "military": false
  },
  {
    "text": "reach out",
    "y2016": true,
    "need": false,
    "matters": false,
    "fact": false,
    "command": true,
    "I": false,
    "We": false,
    "You": true,
    "3rdPersonSingular": false,
    "business": false,
    "politics": false,
    "popCulture": false,
    "scienceTech": false,
    "religion": false,
    "education": false,
    "global": false,
    "community": true,
    "personal": true,
    "fashion": false,
    "military": false
  },
  {
    "text": "we need a Twitter that works",
    "y2016": true,
    "need": true,
    "matters": false,
    "fact": false,
    "command": false,
    "I": false,
    "We": true,
    "You": false,
    "3rdPersonSingular": false,
    "business": false,
    "politics": false,
    "popCulture": true,
    "scienceTech": true,
    "religion": false,
    "education": false,
    "global": true,
    "community": true,
    "personal": false,
    "fashion": false,
    "military": false
  },
  {
    "text": "American open-heartedness is needed",
    "y2016": true,
    "need": true,
    "matters": false,
    "fact": false,
    "command": false,
    "I": false,
    "We": false,
    "You": false,
    "3rdPersonSingular": false,
    "business": false,
    "politics": true,
    "popCulture": false,
    "scienceTech": false,
    "religion": false,
    "education": false,
    "global": true,
    "community": true,
    "personal": false,
    "fashion": false,
    "military": false
  },
  {
    "text": "Thanksgiving has its own rules",
    "y2016": true,
    "need": false,
    "matters": false,
    "fact": true,
    "command": false,
    "I": false,
    "We": false,
    "You": false,
    "3rdPersonSingular": false,
    "business": false,
    "politics": false,
    "popCulture": false,
    "scienceTech": false,
    "religion": false,
    "education": false,
    "global": false,
    "community": true,
    "personal": true,
    "fashion": false,
    "military": false
  },
  {
    "text": "Small Business Saturday matters",
    "y2016": true,
    "need": false,
    "matters": true,
    "fact": false,
    "command": false,
    "I": false,
    "We": false,
    "You": false,
    "3rdPersonSingular": false,
    "business": true,
    "politics": false,
    "popCulture": false,
    "scienceTech": false,
    "religion": false,
    "education": false,
    "global": false,
    "community": true,
    "personal": false,
    "fashion": false,
    "military": false
  },
  {
    "text": "it's time for newspapers",
    "y2016": true,
    "need": false,
    "matters": false,
    "fact": true,
    "command": false,
    "I": false,
    "We": false,
    "You": false,
    "3rdPersonSingular": false,
    "business": true,
    "politics": true,
    "popCulture": false,
    "scienceTech": false,
    "religion": false,
    "education": false,
    "global": true,
    "community": false,
    "personal": false,
    "fashion": false,
    "military": false
  },
  {
    "text": "Ellen DeGeneres' Presidential Medal of Freedom matters",
    "y2016": true,
    "need": false,
    "matters": true,
    "fact": false,
    "command": false,
    "I": false,
    "We": false,
    "You": false,
    "3rdPersonSingular": true,
    "business": false,
    "politics": true,
    "popCulture": true,
    "scienceTech": false,
    "religion": false,
    "education": false,
    "global": false,
    "community": false,
    "personal": false,
    "fashion": false,
    "military": false
  },
  {
    "text": "forward together' is needed",
    "y2016": true,
    "need": true,
    "matters": false,
    "fact": false,
    "command": false,
    "I": false,
    "We": false,
    "You": false,
    "3rdPersonSingular": false,
    "business": false,
    "politics": true,
    "popCulture": false,
    "scienceTech": false,
    "religion": false,
    "education": false,
    "global": false,
    "community": true,
    "personal": false,
    "fashion": false,
    "military": false
  },
  {
    "text": "getting dressed matters",
    "y2016": true,
    "need": false,
    "matters": true,
    "fact": false,
    "command": false,
    "I": false,
    "We": false,
    "You": false,
    "3rdPersonSingular": false,
    "business": false,
    "politics": false,
    "popCulture": true,
    "scienceTech": false,
    "religion": false,
    "education": false,
    "global": false,
    "community": false,
    "personal": false,
    "fashion": true,
    "military": false
  },
  {
    "text": "identity politics matter",
    "y2016": true,
    "need": false,
    "matters": true,
    "fact": false,
    "command": false,
    "I": false,
    "We": false,
    "You": false,
    "3rdPersonSingular": false,
    "business": false,
    "politics": true,
    "popCulture": false,
    "scienceTech": false,
    "religion": false,
    "education": false,
    "global": false,
    "community": false,
    "personal": true,
    "fashion": false,
    "military": false
  },
  {
    "text": "we must stand up for science",
    "y2016": true,
    "need": false,
    "matters": false,
    "fact": false,
    "command": true,
    "I": false,
    "We": true,
    "You": false,
    "3rdPersonSingular": false,
    "business": false,
    "politics": false,
    "popCulture": false,
    "scienceTech": true,
    "religion": false,
    "education": false,
    "global": false,
    "community": false,
    "personal": false,
    "fashion": false,
    "military": false
  },
  {
    "text": "we need to read and be readers",
    "y2016": true,
    "need": true,
    "matters": false,
    "fact": false,
    "command": false,
    "I": false,
    "We": true,
    "You": false,
    "3rdPersonSingular": false,
    "business": false,
    "politics": false,
    "popCulture": true,
    "scienceTech": false,
    "religion": false,
    "education": true,
    "global": false,
    "community": false,
    "personal": false,
    "fashion": false,
    "military": false
  },
  {
    "text": "we need Ursula K. Le Guin",
    "y2016": true,
    "need": true,
    "matters": false,
    "fact": false,
    "command": false,
    "I": false,
    "We": true,
    "You": false,
    "3rdPersonSingular": false,
    "business": false,
    "politics": false,
    "popCulture": true,
    "scienceTech": true,
    "religion": false,
    "education": false,
    "global": false,
    "community": false,
    "personal": false,
    "fashion": false,
    "military": false
  },
  {
    "text": "investors need emotional discipline",
    "y2016": true,
    "need": true,
    "matters": false,
    "fact": false,
    "command": false,
    "I": false,
    "We": false,
    "You": false,
    "3rdPersonSingular": false,
    "business": true,
    "politics": false,
    "popCulture": false,
    "scienceTech": false,
    "religion": false,
    "education": false,
    "global": true,
    "community": false,
    "personal": true,
    "fashion": false,
    "military": false
  },
  {
    "text": "Trump owes us his tax return",
    "y2016": true,
    "need": false,
    "matters": false,
    "fact": true,
    "command": false,
    "I": false,
    "We": false,
    "You": false,
    "3rdPersonSingular": true,
    "business": false,
    "politics": true,
    "popCulture": false,
    "scienceTech": false,
    "religion": false,
    "education": false,
    "global": false,
    "community": false,
    "personal": false,
    "fashion": false,
    "military": false
  },
  {
    "text": "children need us",
    "y2016": true,
    "need": true,
    "matters": false,
    "fact": false,
    "command": false,
    "I": false,
    "We": false,
    "You": false,
    "3rdPersonSingular": false,
    "business": false,
    "politics": false,
    "popCulture": false,
    "scienceTech": false,
    "religion": false,
    "education": false,
    "global": true,
    "community": true,
    "personal": true,
    "fashion": false,
    "military": false
  },
  {
    "text": "we need the unifying power of comedy",
    "y2016": true,
    "need": true,
    "matters": false,
    "fact": false,
    "command": false,
    "I": false,
    "We": true,
    "You": false,
    "3rdPersonSingular": false,
    "business": false,
    "politics": false,
    "popCulture": true,
    "scienceTech": false,
    "religion": false,
    "education": false,
    "global": false,
    "community": true,
    "personal": true,
    "fashion": false,
    "military": false
  },
  {
    "text": "we need Leonard Cohen",
    "y2016": true,
    "need": true,
    "matters": false,
    "fact": false,
    "command": false,
    "I": false,
    "We": true,
    "You": false,
    "3rdPersonSingular": false,
    "business": false,
    "politics": false,
    "popCulture": true,
    "scienceTech": false,
    "religion": false,
    "education": false,
    "global": false,
    "community": false,
    "personal": false,
    "fashion": false,
    "military": false
  },
  {
    "text": "action is needed against the Dakota Access Pipeline",
    "y2016": true,
    "need": true,
    "matters": false,
    "fact": false,
    "command": false,
    "I": false,
    "We": false,
    "You": false,
    "3rdPersonSingular": false,
    "business": true,
    "politics": true,
    "popCulture": false,
    "scienceTech": false,
    "religion": false,
    "education": false,
    "global": false,
    "community": true,
    "personal": false,
    "fashion": false,
    "military": false
  },
  {
    "text": "your Muslim and Sikh neighbors need you",
    "y2016": true,
    "need": true,
    "matters": false,
    "fact": false,
    "command": false,
    "I": false,
    "We": false,
    "You": true,
    "3rdPersonSingular": false,
    "business": false,
    "politics": false,
    "popCulture": false,
    "scienceTech": false,
    "religion": true,
    "education": false,
    "global": true,
    "community": true,
    "personal": false,
    "fashion": false,
    "military": false
  },
  {
    "text": "we need the Olympics",
    "y2016": true,
    "need": true,
    "matters": false,
    "fact": false,
    "command": false,
    "I": false,
    "We": true,
    "You": false,
    "3rdPersonSingular": false,
    "business": true,
    "politics": false,
    "popCulture": true,
    "scienceTech": false,
    "religion": false,
    "education": false,
    "global": true,
    "community": false,
    "personal": false,
    "fashion": false,
    "military": false
  },
  {
    "text": "we need Outlaw Art",
    "y2016": true,
    "need": true,
    "matters": false,
    "fact": false,
    "command": false,
    "I": false,
    "We": true,
    "You": false,
    "3rdPersonSingular": false,
    "business": false,
    "politics": false,
    "popCulture": true,
    "scienceTech": false,
    "religion": true,
    "education": false,
    "global": false,
    "community": false,
    "personal": true,
    "fashion": false,
    "military": false
  },
  {
    "text": "University of Michigan will have to lean on its defense",
    "y2016": true,
    "need": false,
    "matters": false,
    "fact": true,
    "command": false,
    "I": false,
    "We": false,
    "You": false,
    "3rdPersonSingular": false,
    "business": false,
    "politics": false,
    "popCulture": true,
    "scienceTech": false,
    "religion": false,
    "education": true,
    "global": false,
    "community": false,
    "personal": false,
    "fashion": false,
    "military": false
  },
  {
    "text": "we need allies to support the immigrant community",
    "y2016": true,
    "need": true,
    "matters": false,
    "fact": false,
    "command": false,
    "I": false,
    "We": true,
    "You": false,
    "3rdPersonSingular": false,
    "business": false,
    "politics": true,
    "popCulture": false,
    "scienceTech": false,
    "religion": false,
    "education": false,
    "global": true,
    "community": true,
    "personal": false,
    "fashion": false,
    "military": false
  },
  {
    "text": "we need our congressional representatives",
    "y2016": true,
    "need": true,
    "matters": false,
    "fact": false,
    "command": false,
    "I": false,
    "We": true,
    "You": false,
    "3rdPersonSingular": false,
    "business": false,
    "politics": true,
    "popCulture": false,
    "scienceTech": false,
    "religion": false,
    "education": false,
    "global": false,
    "community": false,
    "personal": false,
    "fashion": false,
    "military": false
  },
  {
    "text": "talented civil servants are needed",
    "y2016": true,
    "need": true,
    "matters": false,
    "fact": false,
    "command": false,
    "I": false,
    "We": false,
    "You": false,
    "3rdPersonSingular": false,
    "business": false,
    "politics": true,
    "popCulture": false,
    "scienceTech": false,
    "religion": false,
    "education": false,
    "global": false,
    "community": false,
    "personal": false,
    "fashion": false,
    "military": false
  },
  {
    "text": "protesting matters",
    "y2016": true,
    "need": false,
    "matters": true,
    "fact": false,
    "command": false,
    "I": false,
    "We": false,
    "You": false,
    "3rdPersonSingular": false,
    "business": false,
    "politics": true,
    "popCulture": false,
    "scienceTech": false,
    "religion": false,
    "education": false,
    "global": false,
    "community": false,
    "personal": false,
    "fashion": false,
    "military": false
  },
  {
    "text": "community matters",
    "y2016": true,
    "need": false,
    "matters": true,
    "fact": false,
    "command": false,
    "I": false,
    "We": false,
    "You": false,
    "3rdPersonSingular": false,
    "business": false,
    "politics": false,
    "popCulture": false,
    "scienceTech": false,
    "religion": false,
    "education": false,
    "global": false,
    "community": true,
    "personal": false,
    "fashion": false,
    "military": false
  },
  {
    "text": "proteomics needs better chromatography",
    "y2016": true,
    "need": true,
    "matters": false,
    "fact": false,
    "command": false,
    "I": false,
    "We": false,
    "You": false,
    "3rdPersonSingular": false,
    "business": false,
    "politics": false,
    "popCulture": false,
    "scienceTech": true,
    "religion": false,
    "education": false,
    "global": false,
    "community": false,
    "personal": false,
    "fashion": false,
    "military": false
  },
  {
    "text": "community engagement matters",
    "y2016": true,
    "need": false,
    "matters": true,
    "fact": false,
    "command": false,
    "I": false,
    "We": false,
    "You": false,
    "3rdPersonSingular": false,
    "business": false,
    "politics": false,
    "popCulture": false,
    "scienceTech": false,
    "religion": false,
    "education": false,
    "global": false,
    "community": true,
    "personal": false,
    "fashion": false,
    "military": false
  },
  {
    "text": "we need to embrace 21st-century science, fund it, and turn it loose",
    "y2016": true,
    "need": false,
    "matters": false,
    "fact": false,
    "command": true,
    "I": false,
    "We": true,
    "You": false,
    "3rdPersonSingular": false,
    "business": true,
    "politics": false,
    "popCulture": false,
    "scienceTech": true,
    "religion": false,
    "education": false,
    "global": false,
    "community": false,
    "personal": false,
    "fashion": false,
    "military": false
  },
  {
    "text": "we need school nurses",
    "y2016": true,
    "need": true,
    "matters": false,
    "fact": false,
    "command": false,
    "I": false,
    "We": true,
    "You": false,
    "3rdPersonSingular": false,
    "business": false,
    "politics": false,
    "popCulture": false,
    "scienceTech": false,
    "religion": false,
    "education": false,
    "global": false,
    "community": true,
    "personal": false,
    "fashion": false,
    "military": false
  },
  {
    "text": "understanding how cancer cells can modulate the immune system has become a matter of great importance",
    "y2016": true,
    "need": false,
    "matters": false,
    "fact": true,
    "command": false,
    "I": false,
    "We": false,
    "You": false,
    "3rdPersonSingular": false,
    "business": false,
    "politics": false,
    "popCulture": false,
    "scienceTech": true,
    "religion": false,
    "education": false,
    "global": false,
    "community": false,
    "personal": false,
    "fashion": false,
    "military": false
  },
  {
    "text": "staff in Higher Education need to sharpen their focus on what they do and what they might do to enhance their teaching and support for students",
    "y2016": true,
    "need": false,
    "matters": false,
    "fact": false,
    "command": true,
    "I": false,
    "We": false,
    "You": false,
    "3rdPersonSingular": false,
    "business": false,
    "politics": false,
    "popCulture": false,
    "scienceTech": false,
    "religion": false,
    "education": true,
    "global": false,
    "community": false,
    "personal": false,
    "fashion": false,
    "military": false
  },
  {
    "text": "European parliaments need to legitimate their work and attempt to address the policy challenges faced by Europe",
    "y2016": true,
    "need": false,
    "matters": false,
    "fact": false,
    "command": true,
    "I": false,
    "We": false,
    "You": false,
    "3rdPersonSingular": false,
    "business": false,
    "politics": true,
    "popCulture": false,
    "scienceTech": false,
    "religion": false,
    "education": false,
    "global": true,
    "community": false,
    "personal": false,
    "fashion": false,
    "military": false
  },
  {
    "text": "a large and growing number of children have the potential to develop bilingualism and biliteracy with the support of their families, communities, and teachers",
    "y2016": true,
    "need": false,
    "matters": false,
    "fact": true,
    "command": false,
    "I": false,
    "We": false,
    "You": false,
    "3rdPersonSingular": false,
    "business": false,
    "politics": false,
    "popCulture": false,
    "scienceTech": false,
    "religion": false,
    "education": true,
    "global": false,
    "community": true,
    "personal": false,
    "fashion": false,
    "military": false
  },
  {
    "text": "the changing face of radiation oncology is dependent on an appropriately educated, competent workforce",
    "y2016": true,
    "need": false,
    "matters": false,
    "fact": true,
    "command": false,
    "I": false,
    "We": false,
    "You": false,
    "3rdPersonSingular": false,
    "business": false,
    "politics": false,
    "popCulture": false,
    "scienceTech": true,
    "religion": false,
    "education": true,
    "global": false,
    "community": false,
    "personal": false,
    "fashion": false,
    "military": false
  },
  {
    "text": "an American president risks losing his reputation for power in one theater if he fails to respond adequately to aggression in another",
    "y2016": true,
    "need": false,
    "matters": false,
    "fact": true,
    "command": false,
    "I": false,
    "We": false,
    "You": false,
    "3rdPersonSingular": false,
    "business": false,
    "politics": true,
    "popCulture": false,
    "scienceTech": false,
    "religion": false,
    "education": false,
    "global": true,
    "community": false,
    "personal": false,
    "fashion": false,
    "military": false
  },
  {
    "text": "national governments are obliged to act in the interests of global no less than local capital",
    "y2016": true,
    "need": false,
    "matters": false,
    "fact": false,
    "command": true,
    "I": false,
    "We": false,
    "You": false,
    "3rdPersonSingular": false,
    "business": false,
    "politics": true,
    "popCulture": false,
    "scienceTech": false,
    "religion": false,
    "education": false,
    "global": true,
    "community": true,
    "personal": false,
    "fashion": false,
    "military": false
  },
  {
    "text": "America needs to shift back to a policy of empowering the Cuban people",
    "y2016": true,
    "need": false,
    "matters": false,
    "fact": false,
    "command": true,
    "I": false,
    "We": false,
    "You": false,
    "3rdPersonSingular": false,
    "business": false,
    "politics": true,
    "popCulture": false,
    "scienceTech": false,
    "religion": false,
    "education": false,
    "global": true,
    "community": false,
    "personal": false,
    "fashion": false,
    "military": false
  },
  {
    "text": "it seems pretty unlikely that Rory will ever get her shit together",
    "y2016": true,
    "need": false,
    "matters": false,
    "fact": true,
    "command": false,
    "I": false,
    "We": false,
    "You": false,
    "3rdPersonSingular": true,
    "business": false,
    "politics": false,
    "popCulture": true,
    "scienceTech": false,
    "religion": false,
    "education": false,
    "global": false,
    "community": false,
    "personal": true,
    "fashion": false,
    "military": false
  }
]