var _RawData = [
  {
    "text": "let the dreams of Lombardi trophies dance in your head",
    "y2016": false,
    "need": false,
    "matters": false,
    "fact": false,
    "command": true,
    "business": false,
    "politics": false,
    "global": false,
    "local": false,
    "popCulture": true
  },
  {
    "text": "people need those messages about living well within our geography and current circumstances",
    "y2016": false,
    "need": true,
    "matters": false,
    "fact": false,
    "command": false,
    "business": false,
    "politics": false,
    "global": true,
    "local": true,
    "popCulture": false
  },
  {
    "text": "Arab democracy needs advocates",
    "y2016": false,
    "need": true,
    "matters": false,
    "fact": false,
    "command": false,
    "business": false,
    "politics": true,
    "global": true,
    "local": false,
    "popCulture": false
  },
  {
    "text": "the businesses downtown need  to be patronized",
    "y2016": false,
    "need": true,
    "matters": false,
    "fact": false,
    "command": true,
    "business": true,
    "politics": false,
    "global": false,
    "local": true,
    "popCulture": false
  },
  {
    "text": "people are concerned about helping those who are right around the corner from them",
    "y2016": false,
    "need": false,
    "matters": false,
    "fact": true,
    "command": false,
    "business": false,
    "politics": false,
    "global": false,
    "local": true,
    "popCulture": false
  },
  {
    "text": "engineers need to bring their experience and knowledge to bear to address low-probability, high-consequence system failures",
    "y2016": false,
    "need": true,
    "matters": false,
    "fact": false,
    "command": true,
    "business": false,
    "politics": false,
    "global": false,
    "local": false,
    "popCulture": false
  },
  {
    "text": "the people of America are paying attention to what is going on",
    "y2016": false,
    "need": false,
    "matters": false,
    "fact": true,
    "command": false,
    "business": false,
    "politics": true,
    "global": false,
    "local": false,
    "popCulture": false
  },
  {
    "text": "we need the voice of the people of Boston",
    "y2016": false,
    "need": true,
    "matters": false,
    "fact": false,
    "command": false,
    "business": false,
    "politics": false,
    "global": false,
    "local": true,
    "popCulture": false
  },
  {
    "text": "Port-au-Prince is a city that moves to the rising and setting of the sun",
    "y2016": false,
    "need": false,
    "matters": false,
    "fact": true,
    "command": false,
    "business": false,
    "politics": false,
    "global": true,
    "local": false,
    "popCulture": false
  },
  {
    "text": "the world needs heroes",
    "y2016": false,
    "need": true,
    "matters": false,
    "fact": false,
    "command": false,
    "business": false,
    "politics": true,
    "global": false,
    "local": false,
    "popCulture": false
  },
  {
    "text": "Your mom needs you",
    "y2016": false,
    "need": true,
    "matters": false,
    "fact": false,
    "command": false,
    "business": false,
    "politics": false,
    "global": false,
    "local": true,
    "popCulture": false
  },
  {
    "text": "we need iron discipline",
    "y2016": false,
    "need": true,
    "matters": false,
    "fact": false,
    "command": false,
    "business": false,
    "politics": false,
    "global": false,
    "local": false,
    "popCulture": false
  },
  {
    "text": "conservative culture warriors message is needed",
    "y2016": false,
    "need": true,
    "matters": false,
    "fact": false,
    "command": false,
    "business": false,
    "politics": true,
    "global": false,
    "local": false,
    "popCulture": false
  },
  {
    "text": "We need tax reform",
    "y2016": false,
    "need": true,
    "matters": false,
    "fact": false,
    "command": false,
    "business": true,
    "politics": true,
    "global": false,
    "local": false,
    "popCulture": false
  },
  {
    "text": "Comprehensive immigration reform is needed",
    "y2016": false,
    "need": true,
    "matters": false,
    "fact": false,
    "command": false,
    "business": false,
    "politics": true,
    "global": true,
    "local": false,
    "popCulture": false
  },
  {
    "text": "A safe and effective HIV vaccine is needed",
    "y2016": false,
    "need": true,
    "matters": false,
    "fact": false,
    "command": false,
    "business": false,
    "politics": false,
    "global": false,
    "local": false,
    "popCulture": false
  },
  {
    "text": "Understanding the continuities of long-standing narratives and stereotypes about Haitians and their meaning matter",
    "y2016": false,
    "need": false,
    "matters": true,
    "fact": false,
    "command": false,
    "business": false,
    "politics": true,
    "global": false,
    "local": false,
    "popCulture": false
  },
  {
    "text": "Brandon traversed the streets of his life",
    "y2016": false,
    "need": false,
    "matters": false,
    "fact": false,
    "command": false,
    "business": false,
    "politics": false,
    "global": false,
    "local": true,
    "popCulture": false
  },
  {
    "text": "She needed her mom",
    "y2016": false,
    "need": true,
    "matters": false,
    "fact": false,
    "command": false,
    "business": false,
    "politics": false,
    "global": false,
    "local": true,
    "popCulture": false
  },
  {
    "text": "I need you by my side",
    "y2016": false,
    "need": true,
    "matters": false,
    "fact": false,
    "command": false,
    "business": false,
    "politics": false,
    "global": false,
    "local": true,
    "popCulture": false
  },
  {
    "text": "The fact that the key to the future is, paradoxically, the past has always been true",
    "y2016": false,
    "need": false,
    "matters": false,
    "fact": true,
    "command": false,
    "business": false,
    "politics": false,
    "global": false,
    "local": false,
    "popCulture": false
  },
  {
    "text": "We need to listen to Tony Blair",
    "y2016": true,
    "need": true,
    "matters": false,
    "fact": false,
    "command": true,
    "business": true,
    "politics": true,
    "global": true,
    "local": false,
    "popCulture": false
  },
  {
    "text": "Designers must transform America",
    "y2016": true,
    "need": false,
    "matters": false,
    "fact": false,
    "command": true,
    "business": true,
    "politics": false,
    "global": true,
    "local": false,
    "popCulture": false
  },
  {
    "text": "Kamala Khan is the superhero we need",
    "y2016": true,
    "need": true,
    "matters": false,
    "fact": false,
    "command": false,
    "business": false,
    "politics": false,
    "global": false,
    "local": false,
    "popCulture": true
  },
  {
    "text": "reach out",
    "y2016": true,
    "need": false,
    "matters": false,
    "fact": false,
    "command": true,
    "business": false,
    "politics": false,
    "global": false,
    "local": false,
    "popCulture": false
  },
  {
    "text": "we need a Twitter that works",
    "y2016": true,
    "need": true,
    "matters": false,
    "fact": false,
    "command": false,
    "business": false,
    "politics": false,
    "global": false,
    "local": false,
    "popCulture": true
  },
  {
    "text": "American open-heartedness is needed",
    "y2016": true,
    "need": true,
    "matters": false,
    "fact": false,
    "command": false,
    "business": false,
    "politics": true,
    "global": true,
    "local": false,
    "popCulture": false
  },
  {
    "text": "Thanksgiving has its own rules",
    "y2016": true,
    "need": false,
    "matters": false,
    "fact": true,
    "command": false,
    "business": false,
    "politics": false,
    "global": false,
    "local": false,
    "popCulture": false
  },
  {
    "text": "Small Business Saturday matters",
    "y2016": true,
    "need": false,
    "matters": true,
    "fact": false,
    "command": false,
    "business": true,
    "politics": true,
    "global": false,
    "local": true,
    "popCulture": false
  },
  {
    "text": "it's time for newspapers",
    "y2016": true,
    "need": false,
    "matters": false,
    "fact": true,
    "command": false,
    "business": true,
    "politics": false,
    "global": true,
    "local": true,
    "popCulture": false
  },
  {
    "text": "Ellen DeGeneres' Presidential Medal of Freedom matters",
    "y2016": true,
    "need": false,
    "matters": true,
    "fact": false,
    "command": false,
    "business": false,
    "politics": true,
    "global": false,
    "local": false,
    "popCulture": true
  },
  {
    "text": "'forward together' is needed",
    "y2016": true,
    "need": true,
    "matters": false,
    "fact": false,
    "command": false,
    "business": false,
    "politics": true,
    "global": true,
    "local": true,
    "popCulture": false
  },
  {
    "text": "getting dressed matters",
    "y2016": true,
    "need": true,
    "matters": true,
    "fact": false,
    "command": false,
    "business": false,
    "politics": false,
    "global": false,
    "local": false,
    "popCulture": true
  },
  {
    "text": "identity politics matter",
    "y2016": true,
    "need": false,
    "matters": true,
    "fact": false,
    "command": false,
    "business": false,
    "politics": true,
    "global": false,
    "local": false,
    "popCulture": false
  },
  {
    "text": "we must stand up for science",
    "y2016": true,
    "need": false,
    "matters": false,
    "fact": false,
    "command": true,
    "business": false,
    "politics": false,
    "global": false,
    "local": false,
    "popCulture": false
  },
  {
    "text": "we need to read and be readers",
    "y2016": true,
    "need": true,
    "matters": false,
    "fact": false,
    "command": true,
    "business": false,
    "politics": false,
    "global": false,
    "local": false,
    "popCulture": true
  },
  {
    "text": "we need Ursula K. Le Guin",
    "y2016": true,
    "need": true,
    "matters": false,
    "fact": false,
    "command": false,
    "business": false,
    "politics": false,
    "global": false,
    "local": false,
    "popCulture": true
  },
  {
    "text": "investors need emotional discipline",
    "y2016": true,
    "need": true,
    "matters": false,
    "fact": false,
    "command": false,
    "business": true,
    "politics": false,
    "global": false,
    "local": false,
    "popCulture": false
  },
  {
    "text": "Trump owes us his tax return",
    "y2016": true,
    "need": false,
    "matters": false,
    "fact": true,
    "command": false,
    "business": true,
    "politics": true,
    "global": false,
    "local": false,
    "popCulture": false
  },
  {
    "text": "voters who lost must stay engaged",
    "y2016": true,
    "need": false,
    "matters": false,
    "fact": false,
    "command": true,
    "business": false,
    "politics": true,
    "global": true,
    "local": false,
    "popCulture": false
  },
  {
    "text": "Seattle must welcome upzones",
    "y2016": true,
    "need": false,
    "matters": false,
    "fact": false,
    "command": true,
    "business": true,
    "politics": true,
    "global": false,
    "local": true,
    "popCulture": false
  },
  {
    "text": "children need us",
    "y2016": true,
    "need": true,
    "matters": false,
    "fact": false,
    "command": false,
    "business": false,
    "politics": false,
    "global": true,
    "local": true,
    "popCulture": false
  }
]